paths:
  evaluation_results_dir: "/workspaces/ASE-Model-Retrieval/data/evaluation_results"
  meta_features_dir: "/workspaces/ASE-Model-Retrieval/meta-embedding/.cache/task_embeddings"

model:
  name: "custom_bagging_svc"
  params:
    n_estimators: 10
    num_classes: 93
  # evaluation:
  #   exclude: null
  #   include_only: null

wandb:
  enabled: true
  project: "meta-learner"
  run_name: "svc_bagging_v1"
